### PR TITLE
Detect if users already exists instead of failing. Fixes #431

### LINKED ISSUE #431: Feature: add option to ignore user/group already exists + user already a member of group
**Description**
When running `user.add` and `user.group`, add a boolean option to treat user already exist and user already a group member as not a failure.

**Additional information**
It would be very useful to simply make sure that the user account exists with the specified details, and not fail if the user already exists. Likewise for creating groups and adding users to groups.

If the user already exists, but any of the attributes are different, Comtrya should make the changes.

### PR DESCRIPTION
**Pull request by yonas**
## I'm submitting a

- [x] bug fix
- [ ] feature
- [ ] documentation addition

## What is the current behaviour?
Action `user.add` fails if the user already exists.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
```yaml
actions:
  - action: user.add
    fullname: Test User
    home_dir: /home/test
    username: test
    shell: /bin/sh
```

## What is the expected behavior?
Pass without fail if user already exists.

## What is the motivation / use case for changing the behavior?
Should not be marked as a failing result.

## Please tell us about your environment:

Version (`comtrya --version`): ccdf5e1
Operating system: FreeBSD 14

### CODE REVIEW

File: lib/src/actions/user/add.rs [hunk 1]
```diff
@@ -16,7 +17,14 @@ impl Action for UserAdd {
...
 
-        atoms.append(&mut provider.add_user(&variant)?);
+        if variant.username.is_empty() {
+            return Ok(atoms)
+        }
+
+        match uzers::get_user_by_name(&variant.username) {
+            Some(_user) => debug!(message = "User already exists", username = ?variant.username),
+            None       => atoms.append(&mut provider.add_user(&variant)?)
+        }
```
Comment (martintc) [inline lib/src/actions/user/add.rs:27]: So we will probably need to guard this with conditional compilations so it doesn't get used on Windows, or compiled in to a windows binary, since the uzers crate only works on unix based system.

**Review by martintc — CHANGES_REQUESTED** [review]
Just a single comment regarding adding a conditional compilation guard for use of the uzers crate.

File: lib/src/actions/user/add.rs (hunk 1 above)
Comment (yonas) [reply lib/src/actions/user/add.rs]: Thanks @martintc, I've added a `#[cfg(unix)]` compilation guard.

**Comment by yonas** [comment]
Wait, it needs to add the variant for Windows.

**Comment by martintc** [comment]
I think one last thing, run cargo fmt so it'll pass the linter.

**Comment by yonas** [comment]
Added conditional check when importing `tracing::debug`.

**Review by martintc — APPROVED** [review]

**Comment by martintc** [comment]
Looks like it is good to go, thank you!

**Comment by yonas** [comment]
Yay! Thanks @martintc !
